env:
  CHARTMAN_VERSION: 7bf63961c7afedf4eb2467e2f29e48336bf80946

steps:
  - label: ':docker: build && push'
    command:
      - docker-compose build app
      - docker-compose push app

  - wait

  - label: ":kubernetes: yandex cloud deploy"
    branches: 'ark-2022/cpo'
    agents:
      queue: 'ark-2022/cpo'
    command:
      - aws s3 cp --endpoint-url=https://storage.yandexcloud.net s3://flocktory-helm/chartman/39910c18d71907a625fab39781bc91c40fe2fa7a/chartman-1.0.0.tgz chartman-1.0.0.tgz
      - '/buildkite/scripts/helm.sh chronojob production deploy/chronojob-yac.yaml distribution.flocktory.com/${BUILDKITE_PIPELINE_NAME}:${BUILDKITE_COMMIT}'

  - label: "gitleaks"
    branches: "master"
    command: /buildkite/scripts/gitleaks.sh 
    soft_fail:
      - exit_status: 1
  - wait

  - label: ':s3: Upload'
    command:
      - '/buildkite/scripts/upload-s3.sh chronojob.yaml'
    agents:
      queue: 'eks2'

  - wait

  - label: ':spinnaker: Create spinnaker application'
    command:
      - 'spin application save -f spinnaker/chronojob-application.json'

  - wait

  - label: ':spinnaker: Create spinnaker pipeline'
    command:
      - 'spin pipeline save -f spinnaker/chronojob-pipeline-manual.json'

  - wait

  - label: ':kubernetes: Deploy'
    branches: 'master'
    command:
      - '/buildkite/scripts/spinnaker.sh chronojob'
    agents:
      queue: 'eks2'
