env:
  CHARTMAN_VERSION: 7bf63961c7afedf4eb2467e2f29e48336bf80946

steps:
  - label: ':docker: Build'
    command: docker-compose build app

  - wait

  - label: ':docker: Push'
    command: docker-compose push app

  - wait

  - label: ':s3: Upload'
    command:
      - '/buildkite/scripts/upload-s3.sh chronojob.yaml'
    agents:
      queue: 'eks2'

  - wait

  - label: ':spinnaker: Create spinnaker application'
    command:
      - 'spin application save -f spinnaker/chronojob-application.json'

  - wait

  - label: ':spinnaker: Create spinnaker pipeline'
    command:
      - 'spin pipeline save -f spinnaker/chronojob-pipeline-manual.json'

  - wait

  - label: ':kubernetes: Deploy'
    branches: 'master'
    command:
      - '/buildkite/scripts/spinnaker.sh chronojob'
    agents:
      queue: 'eks2'
